### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by petrnohejl** [doodeec/wedr#1]
```
02-14 11:17:10.280: E/AndroidRuntime(16817): FATAL EXCEPTION: main
02-14 11:17:10.280: E/AndroidRuntime(16817): Process: com.doodeec.weather.android, PID: 16817
02-14 11:17:10.280: E/AndroidRuntime(16817): java.lang.NullPointerException: Attempt to invoke virtual method 'void com.doodeec.weather.android.client.data.model.CurrentCondition.setTimestamp(long)' on a null object reference
02-14 11:17:10.280: E/AndroidRuntime(16817):    at com.doodeec.weather.android.client.data.SessionData.setWeatherData(SessionData.java:59)
02-14 11:17:10.280: E/AndroidRuntime(16817):    at com.doodeec.weather.android.activity.TodayActivity$1.onSuccess(TodayActivity.java:105)
02-14 11:17:10.280: E/AndroidRuntime(16817):    at com.doodeec.weather.android.activity.TodayActivity$1.onSuccess(TodayActivity.java:94)
02-14 11:17:10.280: E/AndroidRuntime(16817):    at com.doodeec.weather.android.client.APIService$1.onSuccess(APIService.java:67)
02-14 11:17:10.280: E/AndroidRuntime(16817):    at com.doodeec.scom.ServerRequest.onPostExecute(ServerRequest.java:66)
02-14 11:17:10.280: E/AndroidRuntime(16817):    at com.doodeec.scom.ServerRequest.onPostExecute(ServerRequest.java:23)
02-14 11:17:10.280: E/AndroidRuntime(16817):    at android.os.AsyncTask.finish(AsyncTask.java:632)
02-14 11:17:10.280: E/AndroidRuntime(16817):    at android.os.AsyncTask.access$600(AsyncTask.java:177)
02-14 11:17:10.280: E/AndroidRuntime(16817):    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
02-14 11:17:10.280: E/AndroidRuntime(16817):    at android.os.Handler.dispatchMessage(Handler.java:102)
02-14 11:17:10.280: E/AndroidRuntime(16817):    at android.os.Looper.loop(Looper.java:135)
02-14 11:17:10.280: E/AndroidRuntime(16817):    at android.app.ActivityThread.main(ActivityThread.java:5221)
02-14 11:17:10.280: E/AndroidRuntime(16817):    at java.lang.reflect.Method.invoke(Native Method)
02-14 11:17:10.280: E/AndroidRuntime(16817):    at java.lang.reflect.Method.invoke(Method.java:372)
02-14 11:17:10.280: E/AndroidRuntime(16817):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
02-14 11:17:10.280: E/AndroidRuntime(16817):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
```

**Comment by dusanbartos** [comment]
fixed by @dd947c1271d1cbc4e2f1c165eefff8b9927dd7d7
